version: "3.8"

services:
  # docker private registry
  docker-registry:
    image: registry:2.8.3
    restart: always
    stdin_open: true
    tty: true
    container_name: docker-registry
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_STORAGE_DELETE_ENABLED='True'
    volumes:
      - $PWD/docker_registry/data:/var/lib/registry
    ports:
      - "5000:5000"
    networks:
      docker-registry-net:
        ipv4_address: 192.168.100.2

  # docker registry frontend
  docker-registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    stdin_open: true
    tty: true
    container_name: docker-registry-frontend
    depends_on:
      - docker-registry
    environment:
      - ENV_DOCKER_REGISTRY_HOST=192.168.100.2
      - ENV_DOCKER_REGISTRY_PORT=5000
    ports:
      - "8080:80"
    networks:
      docker-registry-net:
        ipv4_address: 192.168.100.3

# networks
networks:
  docker-registry-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

